# Generated by Django 4.0 on 2023-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('saved_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'emails_bank',
            },
        ),
    ]
