# Generated by Django 4.0 on 2023-02-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.emailsbank', verbose_name='email_id')),
            ],
            options={
                'db_table': 'campaignhistory',
            },
        ),
    ]
